# Generated by Django 4.2.1 on 2023-05-30 07:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, "0 sinf mavjud emas. Iltimos bohcha bolalarini qo'shmang ;)"), django.core.validators.MaxValueValidator(11, message="O'zbekistonda 11 dan katta sinf yo'qku =)")], verbose_name='Sinf')),
                ('title', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': 'Sinflar',
            },
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name="O'quv yili")),
                ('school_class', models.CharField(max_length=10, verbose_name='Sinflar')),
                ('fullname', models.CharField(max_length=100, verbose_name='F.I.SH')),
                ('date_of_birth', models.DateField(max_length=10, verbose_name="Tug'ilgan yili")),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('start_date', models.DateField(verbose_name='Boshlanish vaqti')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50, verbose_name='Kasbi')),
                ('graphic', models.CharField(max_length=25, verbose_name='Ishlash grafigi')),
                ('start_date', models.DateField(verbose_name='Boshlanish vaqti')),
                ('fullname', models.CharField(max_length=100, verbose_name='F.I.SH')),
                ('date_of_birth', models.DateField(verbose_name="Tug'ilgan yili")),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('inn', models.CharField(max_length=50, verbose_name='INN')),
                ('pinfl', models.CharField(max_length=20, verbose_name='JSHIR')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nomi')),
                ('description', models.CharField(max_length=150, verbose_name="Qisqa ma'lumot")),
                ('image', models.ImageField(upload_to='images/', verbose_name='Rasm')),
                ('classes', models.ManyToManyField(to='members.classnumber')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nomi')),
                ('description', models.CharField(max_length=150, verbose_name="Qisqa ma'lumot")),
                ('url', models.URLField(max_length=50, verbose_name='Dars uchun link')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Rasm')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.subject')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
            },
        ),
    ]
