# Generated by Django 4.2.1 on 2023-06-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_feedback_email_alter_feedback_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('image', models.ImageField(upload_to='posts', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Habar', 'verbose_name_plural': 'Habarlar'},
        ),
    ]
